
export enum GameState {
  RECAP = 'RECAP',
  BOOT_UP = 'BOOT_UP',
  MODULE_CAT = 'MODULE_CAT',
  MODULE_PROPHECY = 'MODULE_PROPHECY',
  MODULE_SNACK = 'MODULE_SNACK',
  MELTDOWN = 'MELTDOWN',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
  FINAL_LOCK = 'FINAL_LOCK',
  EPILOGUE = 'EPILOGUE',
  CHAPTER_2_START = 'CHAPTER_2_START',
  CHAPTER_2_MUSIC = 'CHAPTER_2_MUSIC',
  CHAPTER_2_PERSONALITY = 'CHAPTER_2_PERSONALITY',
  CHAPTER_2_GRATITUDE = 'CHAPTER_2_GRATITUDE',
  CHAPTER_2_RACING = 'CHAPTER_2_RACING',
  CHAPTER_2_LOCK = 'CHAPTER_2_LOCK',
  CHAPTER_2_DEC1 = 'CHAPTER_2_DEC1',
  CHAPTER_2_CONFESSION = 'CHAPTER_2_CONFESSION',
}

export interface Particle {
  id: number;
  x: number;
  y: number;
  size: number;
  color: string;
  duration: number;
  delay: number;
}